### ISSUE TITLE
I get an error with every plist file I try and parse

### ISSUE THREAD

**Issue by joltup** [ciaran/plist#1]
This is the error I get:
*\* (MatchError) no match of right hand side value: "<?xml ve"
    lib/plist.ex:4: Plist.parse/1

**Comment by ciaran** [comment]
This code currently handles binary plists only I’m afraid, as that’s all I needed. If you have a simple/one-off use case you could convert the file to binary using `plutil` first.

If you need XML support I can probably add it though.

**Comment by ciaran** [comment]
I’ve just pushed a quick pass at XML plist parsing, hopefully it suits your case!
